# Generated by Django 4.2.5 on 2023-11-22 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveevent',
            name='user',
        ),
        migrations.CreateModel(
            name='UserEventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('gone', 'Gone'), ('going', 'Going'), ('want_to_go', 'Want to Go')], max_length=10)),
                ('live_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.liveevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='liveevent',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_events', through='users.UserEventStatus', to=settings.AUTH_USER_MODEL),
        ),
    ]
